### PR TITLE
Install g++ in the build environment.

### PR DESCRIPTION
**Pull request by tokkee**

### CODE REVIEW

**Comment by rubenk** [comment]
You beat me by 5 seconds ;)

**Comment by rubenk** [comment]
@mfournier would you be so kind to respin the Xenial scan-build vm? This should fix the build.

**Comment by mfournier** [comment]
@rubenk, @tokkee, I was AFK these past few days. I didn't have the opportunity to go through my collectd backlog yet. But yes, I should be able to take care of this during the WE ;-)

**Comment by rubenk** [comment]
Great, no hurries :)

**Pull request merged**
