### PR TITLE
artifacts: Fix patterns for test logs.

### PR DESCRIPTION
**Pull request by tokkee**
Autotools generate test-suite.log files.

### CODE REVIEW

**Comment by tokkee** [comment]
Was this supposed to be anything else or did anyone see different file names elsewhere?

/cc @mfournier @rubenk

**Comment by rubenk** [comment]
iirc the pattern of how the logs are named depends on the Automake version and if you use the serial or the parallel test harness.

**Comment by tokkee** [comment]
Ah, right. Also, I found test_*.log files for all individual tests in some artifacts, so I guess everything is all right.

**Comment by rubenk** [comment]
It would be nice to have the main test log as well. Could you extend the pattern?

**Comment by tokkee** [comment]
Ack. Updated.

**Comment by rubenk** [comment]
Thanks!

**Pull request merged**
